config/routes.rb
MissedCall::Application.routes.draw do


  get "pages/home"
  root :to => 'pages#home'

  resources :calls
  resources :user_sessions, as: :user_sessions
  resources :users, as: :users
    
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'log_a_call' => 'user_sessions#log_a_call', as: :log_a_call
  mount Resque::Server, :at => "/resque"
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  attr_accessible :username, :email, :password, :password_confirmation, :product
  validates_length_of :password, :minimum => 5, :message => "password must be at least 5 characters long", :if => :password
  validates_confirmation_of :password, :message => "should match confirmation", :if => :password
  validates_uniqueness_of :username, :email
  validates_presence_of :username, :email, :password, :product
  has_many :calls
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :require_login, :only => [:new, :create]
  before_filter :authorize, :only => [:new, :create, :update, :edit]
  # GET /users
  # GET /users.json
  def index
    @users = User.where("admin is null or admin is false")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @call = Call.where(status: "pending")
    unless @user.admin? or @user.product == "all"
      @call = @call.where(call_type: @user.product)
    end
    case @call.count
    when 0..5
      @status = "text text-success"
    when 6..10
      @status = "text text-warning"
    else
      @status = "text text-error"
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to user_path(current_user), notice: "Attendant was created"
    else
      render action: "new" 
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to current_user, notice: 'Attendant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def authorize
    unless current_user && current_user.admin?
      redirect_to root_path, alert: "Not Authorized!"
    end
  end
end

app/views/users/_form.html.erb
<%= simple_form_for(@user, url: user_path(@user), method: :put) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :username %>
    <%= f.input :email %>
    <%= f.input :product, collection: ['engineer','xpress','all'], prompt: "Please select a product" %>
    <%= f.input :password %>
    <%= f.input :password_confirmation %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
    <%= link_to 'Back', user_path(@user), class: "btn" %>
  </div>
<% end %>

app/views/users/_table_row.html.erb
<tr class="row_<%= call.id %>">
  <td><%= call.id %></td>
  <td><%= call.person_mobile %></td>
  <td><%= call.person.try(:person_name) || "N/A" %></td>
  <td><%= call.person.try(:institution_name) || "N/A" %></td>
  <td><%= call.person.try(:person_email) || "N/A" %></td>
  <td><%= call.person.try(:person_state) || "N/A" %></td>
  <td><%= call.updated_at.to_s(:short) %></td>
  <td><a href="/calls/<%= call.id %>/edit" class="btn btn-success">Close</a></td>

app/views/users/edit.html.erb
<h1>Editing User</h1>
<hr>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>Listing Attendants</h1>
<%= link_to 'New Attendant', new_user_path, class: "btn btn-primary" %>
<hr>

<table class="table table-bordered" id="datatables">
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Product</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.product %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br />

app/views/users/new.html.erb
<h1>New User</h1>
<hr>

<%= simple_form_for(@user, url: users_path(@user)) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :username, label: "Name" %>
    <%= f.input :email %>
    <%= f.input :product, collection: ['engineer','xpress','all'], prompt: "Please select a product" %>
    <%= f.input :password %>
    <%= f.input :password_confirmation %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
    <%= link_to 'Back', root_path, class: "btn" %>
  </div>
<% end %>

app/views/users/show.html.erb
<div class="row">
  <h1 style="font-size: 450%;"><%= content_tag :div, pluralize(@call.count.to_s, " Pending Call"), class: @status + " span12 center call_count" %></h1>
</div>
<hr>

<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Call from</th>
      <th>Name</th>
      <th>Institution</th>
      <th>Email</th>
      <th>State</th>
      <th>Updated At</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody class="table_body">
    <% @call.each do |call| %>
    <%= render 'table_row', call: call %>
    <% end -%>
  </tbody>
</table>
<%= tag "div", class: "call-count", data: { count: @call.count } %>
<% if @user.admin? or @user.product == "all" -%>
  <%= subscribe_to "/calls/engineer" %>
  <%= subscribe_to "/calls/xpress" %>
  <%= tag "div", class: "channel-data", data: { call: ["/calls/engineer", "/calls/xpress"] } %>
<% else -%>
  <%= subscribe_to "/calls/#{@user.product}" %>
  <%= tag "div", class: "channel-data", data: { call: ["/calls/#{@user.product}"] } %>
<% end -%>