config/routes.rb
MissedCall::Application.routes.draw do


  get "pages/home"
  root :to => 'pages#home'

  resources :calls
  resources :user_sessions, as: :user_sessions
  resources :users, as: :users
    
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'log_a_call' => 'user_sessions#log_a_call', as: :log_a_call
  mount Resque::Server, :at => "/resque"
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_filter :require_login, :except => [:destroy]
  def new
    current_user and redirect_to user_path(current_user)
    @user = User.new
  end

  def create
    respond_to do |format|
      if @user = login(params[:email],params[:password])
        format.html { redirect_back_or_to(user_path(@user), :notice => 'Login successful.') }
        format.xml { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { flash.now[:alert] = "Login failed."; render :action => "new" }
        format.xml { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    logout
    redirect_to(root_path, :alert => 'Logged out!')
  end

  def log_a_call
    Resque.enqueue(DataEntryResque, params[:mobile], params[:type])
    render nothing: true
  end
end

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post do %>
  <div class="form-inputs">
      <%= label_tag :email %>
      <%= text_field_tag :email %>
      <%= label_tag :password %>
      <%= password_field_tag :password %>
  </div>
    <div class="form-inputs">
      <hr>
      <%= submit_tag "   Login   ", class: "btn btn-primary" %>
    </div>
<% end %>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<h1>Login</h1>
<hr>

<%= render 'form' %>