config/routes.rb
MissedCall::Application.routes.draw do


  get "pages/home"
  root :to => 'pages#home'

  resources :calls
  resources :user_sessions, as: :user_sessions
  resources :users, as: :users
    
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'log_a_call' => 'user_sessions#log_a_call', as: :log_a_call
  mount Resque::Server, :at => "/resque"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Forbes Technosys Ltd." %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
  </head>
  <body>

    <div class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <% if current_user -%>
            <% link = user_path(current_user) -%>
          <% else -%>
            <% link = root_path -%>
          <% end -%>
          <a class="brand" href="<%= link %>" style="color: #fff;">Missed Call Alerts</a>
          <div class="container nav-collapse">
            <ul class="nav pull-right">
              <% if current_user -%>
                <% if current_user && current_user.admin? %>
                  <li><%= link_to "Register Attendant", new_user_path %></li>
                  <li><%= link_to "Attendant List", users_path %></li>
                  <li><%= link_to "Reports", calls_path %></li>
                <%- end %>
                <li><%= link_to "Logout", :logout %></li>
              <% else -%>
                <li><%# link_to "Login", :login %></li>
              <% end -%>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
            <br><br><br>
            <% flash.each do |name, msg| %>
              <% unless msg.blank? -%>
                <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
                  <a class="close" data-dismiss="alert">&#215;</a>
                  <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
                </div>
              <% end %>
            <% end -%>
          <div class="span12">
             <%= yield %>
          </div>
        </div><!--/row-->

      <footer class="center">
        <%# <p>&copy; Forbes Technosys Ltd. 2012</p>%>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

  </body>
</html>